// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/03/2025, 16:44:51
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Ultrabook Design i7/Desktop/python chain/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ultrabook Design i7/Desktop/python chain/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ultrabook Design i7/Desktop/python chain/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ultrabook Design i7/Desktop/python chain/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ultrabook Design i7/Desktop/python chain/plugins/**/*.{js,ts,mjs}","C:/Users/Ultrabook Design i7/Desktop/python chain/composables/**/*.{js,ts,mjs}","C:/Users/Ultrabook Design i7/Desktop/python chain/utils/**/*.{js,ts,mjs}","C:/Users/Ultrabook Design i7/Desktop/python chain/pages/index.vue","C:/Users/Ultrabook Design i7/Desktop/python chain/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ultrabook Design i7/Desktop/python chain/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Ultrabook Design i7/Desktop/python chain/app.config.{js,ts,mjs}","C:/Users/Ultrabook Design i7/Desktop/python chain/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;